### ISSUE TITLE
v0.4: Dimension Font Crop,Theme goes crazy,Line Anti-aliasing,Viewport vs Render difference

### ISSUE THREAD

**Issue by tilakji** [kevancress/MeasureIt-ARCH#85]
First of all,Kudos to Antonio Vazquez, kevancress (you) and all of the blender developers and add-ons developers for it.
Thanks!

B3D v2.81.16 | add-on v0.4 | Linux (ArchLinux base)
i7 | GTX1060 | NVIDIA driver v418.113 
issues:
• Dimension Font gets cropped.  (ref font: flux architect)
![MiArch_issue_textcrop_screenshot](https://user-images.githubusercontent.com/66463808/83853179-82a0c880-a732-11ea-8ec4-b6e340626650.png)

• Theme goes crazy after hitting "Measure-it ARCH Image" when used in a project that had around 50k faces
-Before
![MiArch_issue_before-themegoescrazy_screenshot](https://user-images.githubusercontent.com/66463808/83854427-51c19300-a734-11ea-8ef2-ca1bf35c1168.png)
-After
![MiArch_issue_after-themegoescrazy_screenshot](https://user-images.githubusercontent.com/66463808/83854519-761d6f80-a734-11ea-956c-c01a96c6adc3.png)
(UI Text/theme render-flaw exists till app restart,thus drops a huge roadblock)

improvement:
• Need better anti-aliasing
![MiArch_issue_betterantialias_screenshot](https://user-images.githubusercontent.com/66463808/83853528-08247880-a733-11ea-9ef0-81f767563c94.png)

• Dimension position differs, comparing Viewport vs Dimension Render. 
-Viewport:
![MiArch_issue_textcrop_screenshot](https://user-images.githubusercontent.com/66463808/83853179-82a0c880-a732-11ea-8ec4-b6e340626650.png)
Versus
-Dimension Render Composite:
![MiArch_issue_betterantialias_screenshot](https://user-images.githubusercontent.com/66463808/83853528-08247880-a733-11ea-9ef0-81f767563c94.png)
Please clarify if that is intended to work like that. or we have option to tweak that?
and
• Displaying, eg. 2' 12" as 3' would be neat!
![MiArch_issue_textcrop_screenshot](https://user-images.githubusercontent.com/66463808/83853179-82a0c880-a732-11ea-8ec4-b6e340626650.png)

Thanks!

**Comment by kevancress** [comment]
Hey @tilakji Thanks for the feedback!

I've just pushed a fix first two major issues, (text clipping and UI error) and the imperial rounding error so they should be resolved in the latest master. If you can give it a test and let me know if the fix works for you that would be great!

For the other issues:

Anti-aliasing: A local AA solution for measureIt-ARCH is in the works, you can see how its coming along if you look at the AA on the line group lines. Right now my implementation breaks down for thin lines, so I haven't implemented it for dimension leader lines yet. I'm taking a lot of inspiration from the [shapes library](https://twitter.com/FreyaHolmer/status/1255193781739180032) being developed for unity right now, so hopefully we'll get to that level of line quality soon.

Render vs. Viewport position: Right now, if you don't have a view plane specified, dimensions are positioned based on the users viewpoint in the 3d scene. So a general perspective view won't necessarily match the render and that's intentional to try and keep the dimension legible when working in the viewport. That said, the dimensions position in the camera preview view should always match the render so you can accurately preview the drawing you want to export. If it doesn't match the camera view let me know and I'll try and get that fixed.

**Comment by kevancress** [comment]
Hey @tilakji, I'm closing this issue for now since I think the Major Problems you identified are resolved. 

re Render vs. Viewport position: If this is still an issue based on the comments above, please let me know and open a new issue report for it, Thanks!

**Comment by tilakji** [comment]
hello @kevancress ! sorry for late reply,stuck somewhere.
just downloaded 2.83 LTS, i will check our MeasureIt-Arch's latest release with that and report to you.
Thanks!!!

**Comment by HarryC1** [comment]
Hi
0.4 shows image shows a dimension but I still can’t get I right. I’m waiting for the video which might describe how to get the dimension and the arch.
